# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0fb335c277c1af4ee2a94e793a414f1281fbe85e3e937e47929438b3f6cd2a0cfb2b797dba45355f7230a417183224fd74011c64c35ecc4c9d13c71fc1554f

test:
  secret_key_base: c5bf1e475baffeedef1bf7681f6c91005ef94391d8c238d61696e413fee9e263b556f04db1a01e6785cccaf4913aa2ed925faa532b0eea42ad29760ac10528c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
